version: '3.8'

services:
  db:
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: opencommerce
      POSTGRES_PASSWORD: opencommerce
    networks:
      - opencommerce-backend
networks:
  opencommerce-backend:
